USE CODE_HELP;
DROP TABLE IF EXISTS CH_USERS;

CREATE TABLE CH_USERS (
    `USER_ID` VARCHAR(200) NOT NULL UNIQUE,
    `SIGN_PROVIDER` ENUM ('google.com', 'facebook') NOT NULL,
    `EMAIL` VARCHAR(200) NOT NULL,
	`DISPLAY_NAME` VARCHAR(200) NOT NULL,
    `PHOTO` VARCHAR(200) NULL,
	`PHONE` VARCHAR(30) NULL,
	`ACTIVE` TINYINT NOT NULL,
    PRIMARY KEY(USER_ID)
);

INSERT INTO CH_USERS VALUES
  ('1','google.com','email','display','photo','PHONE',1);