USE `TEST`;


-- DROPPING TABLES
DROP TABLE IF EXISTS SG_GROUP_FORMATIONS;
DROP TABLE IF EXISTS SG_GROUPS;
DROP TABLE IF EXISTS SG_TOURNAMENTS;
DROP TABLE IF EXISTS SG_TEAMS;

-- CREATES A TABLE CONTAINING ALL TOURNAMENTS
CREATE TABLE IF NOT EXISTS `SG_TOURNAMENTS` (
    `ID` TINYINT NOT NULL UNIQUE AUTO_INCREMENT,
    `NAME` VARCHAR(150) NOT NULL,	
    `FLAG` VARCHAR(255) NULL DEFAULT 'team_flag.png',
    `ACTIVE` TINYINT(1) NULL DEFAULT 1,
    PRIMARY KEY(ID)
);

-- CREATES A TABLE CONTAINING ALL TEAMS
CREATE TABLE `SG_TEAMS` (
  `ID`         INT NOT NULL AUTO_INCREMENT,
  `FULLNAME`   VARCHAR(100) NOT NULL UNIQUE,
  `SHORTNAME`  CHAR(3) NOT NULL,
  `FLAG`       VARCHAR(255) DEFAULT 'team_flag.png',
  `ACTIVE`	   TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY(ID)
);

-- CREATES A TABLE CONTAINING ALL GROUPS OF ALL TOURNAMENTS
CREATE TABLE `SG_GROUPS` (
	`ID` INT NOT NULL UNIQUE AUTO_INCREMENT,
	`NAME` VARCHAR(2) NOT NULL ,
    `TOURNAMENT_ID` TINYINT NOT NULL,
	`ACTIVE` TINYINT(1) NULL DEFAULT 1,
    PRIMARY KEY(NAME,TOURNAMENT_ID),  
	FOREIGN KEY(TOURNAMENT_ID) REFERENCES SG_TOURNAMENTS(ID) 
);

-- CREATES A TABLE CONTAINING ALL GROUPS FORMATIONS
CREATE TABLE IF NOT EXISTS SG_GROUP_FORMATIONS (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `TEAM_ID` INT NOT NULL,	 
	`GROUP_ID` INT NOT NULL,
	 PRIMARY KEY(ID),
     FOREIGN KEY(TEAM_ID) REFERENCES SG_TEAMS(ID),
	 FOREIGN KEY(GROUP_ID) REFERENCES SG_GROUPS(ID),
     CONSTRAINT `unique_combination_GP` UNIQUE(GROUP_ID,TEAM_ID)
);


-- CREATES A TABLE FOR CONTAINING ALL USERS
-- CREATE TABLE SG_USERS  

    
CREATE TABLE IF NOT EXISTS `SG_USERS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`EMAIL` VARCHAR(255) NOT NULL,
	`PASS` VARCHAR(45) NULL,
	`FIRSTNAME` VARCHAR(255) NULL,
	`LASTNAME` VARCHAR(255) NULL,
	`SIGN_TYPE` ENUM('google', 'facebook', 'root') NULL,
	`ACTIVE` VARCHAR(45) NULL,
	`CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`LAST_UPDATED` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
); 

-- INSERT INTO SG_TOURNAMENTS VALUES
--     (NULL, "SOUTH AMERCIA'S QUALIFIERS 2022",NULL,1),
--     (NULL, "WORLD CUP 2018",NULL,1);
-- 
-- INSERT INTO SG_GROUPS (`NAME`,`TOURNAMENT_ID`)VALUES 
--   ("A",1),
--   ("A",2),
--   ("B",2),
--   ("C",2),
--   ("D",2),
--   ("E",2),
--   ("F",2),
--   ("G",2),
--   ("H",2),
--   ("I",2),
--   ("J",2),
--   ("K",2),
--   ("L",2);
-- 
-- INSERT INTO SG_TEAMS VALUES
--   (NULL,'brazil','1','brazil.png',1),
--   (NULL,'germany','2','germany.png',1),
--   (NULL,'URUGUAI','3','URUGUAI.png',1),
--   (NULL,'ITALY','4','ITALY.png',1),
--   (NULL,'CHILE','5','CHILE.png',1),
--   (NULL,'france','6','france.png',1),
--   (NULL,'spain','7','spain.png',1),
--   (NULL,'argentina','8','argentina.png',1),  
--   (NULL,'colombia','9','colombia.png',1),
--   (NULL,'england','10','england.png',1),
--   (NULL,'japan','11','japan.png',1),
--   (NULL,'china','12','china.png',1),
--   (NULL,'EQUADOR','13','EQUADOR.png',1),
--   (NULL,'PORTUGAL','14','PORTUGAL.png',1);
-- 
-- INSERT INTO SG_GROUP_FORMATIONS (TEAM_ID,GROUP_ID) VALUES 
-- (1,1),
-- (2,2),
-- (3,1),
-- (4,2),
-- (5,1),
-- (6,2),
-- (7,2),
-- (8,1),
-- (9,1),
-- (10,3),
-- (11,3),
-- (12,3),
-- (13,3),
-- (14,4);
-- 
-- -- 
-- SELECT * FROM `SG_GROUPS`;